apps/accounts/urls.py
"""
URL patterns in lending app
"""
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import Login, PasswordChange

app_name = "accounts"
urlpatterns = [
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password-change/", PasswordChange.as_view(), name="password-change"),
]

apps/lending/urls.py
"""
URL patterns in lending app
"""
from django.urls import path

from .views import (
    ActiveLoans,
    BorrowerDetail,
    EarningsGraph,
    LoanSourcesGraph,
    MoneyReturnedGraph,
    PastDueList,
    UpcomingDueList,
)

app_name = "lending"
urlpatterns = [
    path("earnings-graph/", EarningsGraph.as_view(), name="earnings-graph"),
    path("loan-sources-graph/", LoanSourcesGraph.as_view(), name="loan-sources-graph"),
    path(
        "money-returned-graph/",
        MoneyReturnedGraph.as_view(),
        name="money-returned-graph",
    ),
    path("amortization/past-due/", PastDueList.as_view(), name="past-due-list"),
    path(
        "amortization/upcoming-due/",
        UpcomingDueList.as_view(),
        name="upcoming-due-list",
    ),
    path("loans/active/", ActiveLoans.as_view(), name="loans-active"),
    path("borrowers/<uuid:pk>/", BorrowerDetail.as_view(), name="borrowers-detail"),
]

sharky/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.safestring import mark_safe

from . import views

admin.site.site_title = admin.site.index_title = "sharky backend"
admin.site.site_header = mark_safe(
    '<img src="{img}" alt="{alt}"/>'.format(
        img=settings.STATIC_URL + "admin/img/logo-140x60.png",
        alt=admin.site.site_title,
    )
)


urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("lending/", include("apps.lending.urls")),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("", views.Index.as_view(), name="index"),
    # Administration
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sharky/views.py
import math
from typing import Any, Dict, Optional

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Case, Count, DecimalField, F, Q, Sum, Value, When
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import RedirectView, TemplateView

from apps.lending.models import Amortization, CapitalSource, Loan, LoanSource


class Dashboard(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    """
    Displays the dashboard page.
    """

    template_name = "index.html"

    def test_func(self) -> Optional[bool]:
        return self.request.user.is_superuser

    def get_past_due_amortizations(self) -> int:
        """
        Returns the number of past due amortizations.
        """
        return (
            Amortization.objects.filter(
                due_date__lte=timezone.now(),
                paid_date__isnull=True,
            )
            .exclude(
                loan__borrower__is_borrower_active=False,
            )
            .count()
        )

    def get_active_loans(self) -> int:
        """
        Returns the number of active loans.
        """
        return (
            Loan.objects.filter(
                is_completed=False,
            )
            .exclude(
                borrower__is_borrower_active=False,
            )
            .count()
        )

    def get_earnings_for_current_month(self) -> int:
        """
        Returns the earnings from all loans for the current month.
        """
        now = timezone.now()
        amortizations = (
            Amortization.objects.filter(
                due_date__month=now.month,
                due_date__year=now.year,
                is_preterminated=False,
            )
            .exclude(
                loan__borrower__is_borrower_active=False,
            )
            .aggregate(
                total_gained=Sum("amount_gained"),
            )
        )
        return amortizations["total_gained"] or 0

    def get_total_principal_receivables(self) -> int:
        """
        Returns the total principal receivables for all active loans with source coming
        from a savings account.
        """

        sources = (
            LoanSource.objects.filter(
                capital_source__source=CapitalSource.SOURCES.savings,
                capital_source__provider__isnull=True,
            )
            .exclude(
                loan__borrower__is_borrower_active=False,
            )
            .annotate(
                receivables=Case(
                    When(
                        loan__payment_schedule=Loan.PAYMENT_SCHEDULES.monthly,
                        then=(
                            F("amount")
                            / F("loan__term")
                            * Count(
                                "loan__amortizations",
                                filter=Q(loan__amortizations__paid_date__isnull=True),
                            )
                        ),
                    ),
                    When(
                        loan__payment_schedule=Loan.PAYMENT_SCHEDULES.bi_monthly,
                        then=(
                            (F("amount") / F("loan__term"))
                            * (
                                Count(
                                    "loan__amortizations",
                                    filter=Q(
                                        loan__amortizations__paid_date__isnull=True
                                    ),
                                )
                            )
                            / 2
                        ),
                    ),
                    default=Value(0),
                    output_field=DecimalField(),
                )
            )
            .aggregate(total=Sum("receivables"))
        )

        return math.floor(sources["total"] or 0)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "active_loans": self.get_active_loans(),
                "current_month_earnings": self.get_earnings_for_current_month(),
                "total_principal_receivables": self.get_total_principal_receivables(),
                "past_due_amortizations": self.get_past_due_amortizations(),
            }
        )
        return context


class Index(RedirectView):
    """
    Redirects to the corresponding pages when index page is accessed.
    """

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> Optional[str]:
        """
        Returns the URL to redirect to.
        """
        user = self.request.user
        if user.is_authenticated and user.is_superuser:
            return reverse_lazy("dashboard")
        elif user.is_authenticated and user.is_borrower:
            return reverse_lazy("lending:borrowers-detail", args=(user.pk,))
        else:
            return reverse_lazy("accounts:login")

sharky/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load humanize %}
{% load static %}
{% load i18n %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sharky - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    {% block extra_css %}
    {% endblock %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-hand-holding-usd"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Sharky</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            {% if request.user.is_superuser %}
              <!-- Nav Item - Dashboard -->
              <li class="nav-item {% block nav_dashboard %}{% endblock %}">
                  <a class="nav-link" href="{% url 'dashboard' %}">
                      <i class="fas fa-fw fa-tachometer-alt"></i>
                      <span>Dashboard</span></a>
              </li>

            {% else %}
              <!-- Nav Item - Dashboard -->
              <li class="nav-item {% block nav_profile %}{% endblock %}">
                <a class="nav-link" href="{% url 'lending:borrowers-detail' request.user.pk %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
              </li>
              <!-- Divider -->
              <hr class="sidebar-divider">
            {% endif %}

            <!-- Heading -->
            <div class="sidebar-heading">
                Loans
            </div>

            <!-- Nav Item - Amortizations -->
            <li class="nav-item {% if show_amortization_menu %}active{% endif %}">
                <a class="nav-link {% if not show_amortization_menu %}collapsed{% endif %}" href="#" data-toggle="collapse" data-target="#collapseAmortizations"
                    aria-expanded="{% if show_amortization_menu %}true{% else %}false{% endif %}" aria-controls="collapseAmortizations">
                    <i class="fas fa-fw fa-file-invoice-dollar"></i>
                    <span>{% trans "Amortizations" %}</span>
                </a>
                <div id="collapseAmortizations" class="collapse {% if show_amortization_menu %}show{% endif %}" aria-labelledby="headingBorrowers"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Amortizations:</h6> -->
                        <a class="collapse-item {% block nav_past_due %}{% endblock %}" href="{% url 'lending:past-due-list' %}">
                            {% trans "Past Due" %}
                        </a>
                        <a class="collapse-item {% block nav_upcoming_due %}{% endblock %}" href="{% url 'lending:upcoming-due-list' %}">
                            {% trans "Upcoming Due" %}
                        </a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Active Loans -->
            <li class="nav-item {% block nav_active_loans %}{% endblock %}">
            <a class="nav-link" href="{% url 'lending:loans-active' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Active Loans</span></a>
            </li>

            {% if request.user.is_superuser %}
                <!-- Nav Item - Borrowers -->
                <li class="nav-item {% block nav_borrowers %}{% endblock %}">
                    <a class="nav-link {% if not borrower %}collapsed{% endif %}" href="#" data-toggle="collapse" data-target="#collapseBorrowers"
                        aria-expanded="{% if borrower %}true{% else %}false{% endif %}" aria-controls="collapseBorrowers">
                        <i class="fas fa-fw fa-users"></i>
                        <span>{% trans "Borrowers" %}</span>
                    </a>
                    <div id="collapseBorrowers" class="collapse {% if borrower %}show{% endif %}" aria-labelledby="headingBorrowers"
                        data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <!-- <h6 class="collapse-header">Borrowers:</h6> -->
                            {% for brwr in borrowers_list %}
                                <a class="collapse-item {% if borrower == brwr %}active{% endif %}" href="{% url 'lending:borrowers-detail' brwr.pk %}">
                                    {{ brwr.get_full_name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </li>
            {% endif %}

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.get_full_name }}</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile_3.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'accounts:password-change' %}">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Change Password
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <div {% if message.tags %} class=" alert alert-{{ message.tags }} " {% endif %}>
                                {{ message }}
                            </div>
                        {% endfor %}
                    </ul>
                    {% endif %}

                    {% block content %}
                    {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Sharky 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <script type="text/javascript">
        window.earningsGraphUrl = "{% url 'lending:earnings-graph' %}";
        window.LoanSourcesGraphUrl = "{% url 'lending:loan-sources-graph' %}";
        window.moneyReturnedGraphUrl = "{% url 'lending:money-returned-graph' %}";
    </script>

    {% block extra_js %}
    {% endblock %}

</body>

</html>

sharky/templates/index.html
{% extends "base.html" %}

{% load humanize %}
{% load static %}

{% block nav_dashboard %}active{% endblock %}

{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Earnings (Current Month)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ current_month_earnings|intcomma }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-coins fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Total Principal Receivables</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ total_principal_receivables|intcomma }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                Past Due Amortization</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ past_due_amortizations }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                Active Loans</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ active_loans }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-book-open fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Money Returned Graph -->
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Amount Received Monthly</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="moneyReturnedGraph"></canvas>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="clearfix">&nbsp;</div>

    <div class="row">

        <!-- Projected Monthly Income Chart -->
        <div class="col-xl-8 col-lg-8">
            <div class="card shadow mb-8">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Monthly Interest and Principal Receivables</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="earningsGraph"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-4 col-lg-4">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Loan Sources</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <div class="mt-4 text-center small">
                        <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Savings Account
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> Credit Card
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Cash Loan
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">



        <div class="clearfix">&nbsp;</div>
    </div>

{% endblock %}

{% block extra_js %}

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'base/js/earnings-graph.js' %}"></script>
    <script src="{% static 'base/js/money-returned-graph.js' %}"></script>
    <script src="{% static 'base/js/loan-sources-graph.js' %}"></script>

{% endblock %}

sharky/templates/login.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sharky - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    {% if form.errors %}
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                        {% for error in form.non_field_errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                    <form class="user" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ form.username }}
                                        </div>
                                        <div class="form-group">
                                            {{ form.password }}
                                        </div>
                                        <input type="submit" class="btn btn-primary btn-user btn-block" value="Login" />
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

</body>

</html>